@baseUrl=http://localhost:5000
@urlPath=api/v1
# Antar1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWEyMzE3MDE5N2RkZDJjNzA5NjgxNzciLCJ1SWQiOiIyMzU0MjM0MDM3NTAiLCJlbWFpbCI6ImRldi5hbnRhcmRhc0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkFudGFyIiwiYXZhdGFyQ29sb3IiOiJibGFjayIsImlhdCI6MTcwNjQzMjM5M30.X57z1x8aMMGmypzXlnLruxVV_wxMjXnYZ3Dw0ZCZH0U
@notificationId=65b5aefee30dab82576e0034
@userTo=65a23170197ddd2c70968177

### Mark as Read
PUT  {{baseUrl}}/{{urlPath}}/notifications/{{notificationId}}
Content-Type: application/json
Accept: application/json
withCredentials: true
Authorization: {{token}}

{
}
### Get ALl Notification 
GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true
Authorization: {{token}}

{
}


### Delete Notifincation
DELETE {{baseUrl}}/{{urlPath}}/notifications/{{notificationId}}
Content-Type: application/json
Accept: application/json
withCredentials: true
Authorization: {{token}}

{
}