version: '3'
services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:./data/cache:rw
    ports:
      - "6379:6379"
volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/cache
      o: bind