version: '3'

services:
  redis:
    image: redis:latest
    container_name: chithi-redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
    command: redis-server redis.conf
  # localstack:
  #   container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
  #   image: localstack/localstack-pro
  #   restart: on-failure
  #   ports:
  #     - '127.0.0.1:4566:4566' # LocalStack Gateway
  #     - '127.0.0.1:4510-4559:4510-4559' # external services port range
  #   environment:
  #     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #     - DEBUG=${DEBUG:-1}
  #     - LOCALSTACK_AUTH_TOKEN="ls-JoZE8259-BEwE-8883-Dole-LirOQoca10cc"
  #     - LOCALSTACK_PERSISTENCE=0
  #   volumes:
  #     - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  caddy_data:
  caddy_config: