version: '3'

services:
  redis:
    image: redis:latest
    container_name: chithi-redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
    command: redis-server redis.conf